name: test-deploy-based-on-push 
on: push
jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci 
      - name: test dependencies
        run: npm run test
      - name: build dependencies 
        run: npm run build
      - name: deploye dependencies 
        run: echo "deploy"
